# -*- coding: utf-8 -*-
"""automate_bayu-Septiawan.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fX5_B2QPe5wERkWR0WHOnyreMLWSZBiJ
"""

# automate_student.py

"""
AUTOMATED DATA PREPROCESSING MODULE
Wine Quality Dataset

Module ini mengotomasi seluruh proses preprocessing dari notebook eksperimen.
Digunakan untuk memproses data secara konsisten dan reproducible.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import os
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class WineQualityPreprocessor:
    """
    Class untuk mengotomasi preprocessing Wine Quality Dataset
    """

    def __init__(self, raw_data_path: str, output_dir: str = 'wine_quality_preprocessing'):
        """
        Inisialisasi preprocessor

        Args:
            raw_data_path (str): Path ke file raw data (CSV)
            output_dir (str): Directory untuk menyimpan hasil preprocessing
        """
        self.raw_data_path = raw_data_path
        self.output_dir = output_dir
        self.df = None
        self.X = None
        self.y = None
        self.scaler = StandardScaler()

        # Buat output directory jika belum ada
        os.makedirs(output_dir, exist_ok=True)
        logger.info(f"Output directory: {output_dir}")

    def load_data(self) -> pd.DataFrame:
        """Load raw data"""
        try:
            self.df = pd.read_csv(self.raw_data_path)
            logger.info(f"✓ Data loaded successfully. Shape: {self.df.shape}")
            return self.df
        except FileNotFoundError:
            logger.error(f"✗ File not found: {self.raw_data_path}")
            raise

    def handle_missing_values(self) -> pd.DataFrame:
        """Menangani missing values dengan median"""
        logger.info("Processing: Handle Missing Values")

        missing_count = self.df.isnull().sum().sum()
        logger.info(f"  Missing values found: {missing_count}")

        if missing_count > 0:
            self.df = self.df.fillna(self.df.median(numeric_only=True))
            logger.info(f"  ✓ Missing values filled with median")
        else:
            logger.info(f"  ✓ No missing values")

        return self.df

    def remove_duplicates(self) -> pd.DataFrame:
        """Menghapus data duplikat"""
        logger.info("Processing: Remove Duplicates")

        duplicates_before = self.df.duplicated().sum()
        logger.info(f"  Duplicates found: {duplicates_before}")

        self.df = self.df.drop_duplicates()

        logger.info(f"  ✓ Duplicates removed. Shape after: {self.df.shape}")
        return self.df

    def detect_outliers(self, method: str = 'iqr') -> dict:
        """
        Deteksi outliers (untuk informasi, tidak dihapus)

        Args:
            method (str): 'iqr' atau 'zscore'

        Returns:
            dict: Informasi outliers
        """
        logger.info("Processing: Detect Outliers (IQR Method)")

        if method == 'iqr':
            Q1 = self.df.quantile(0.25)
            Q3 = self.df.quantile(0.75)
            IQR = Q3 - Q1

            outliers_mask = ((self.df < (Q1 - 1.5 * IQR)) |
                           (self.df > (Q3 + 1.5 * IQR))).any(axis=1)
            outlier_count = outliers_mask.sum()

            logger.info(f"  Outliers detected: {outlier_count} ({(outlier_count/len(self.df))*100:.2f}%)")
            logger.info(f"  Note: Outliers are retained (not removed)")

            return {
                'method': 'iqr',
                'count': outlier_count,
                'percentage': (outlier_count / len(self.df)) * 100
            }

        return {}

    def separate_features_target(self, target_col: str = 'quality') -> tuple:
        """
        Memisahkan features dan target

        Args:
            target_col (str): Nama kolom target

        Returns:
            tuple: (X, y)
        """
        logger.info("Processing: Separate Features and Target")

        self.X = self.df.drop(target_col, axis=1)
        self.y = self.df[target_col]

        logger.info(f"  Features shape: {self.X.shape}")
        logger.info(f"  Target shape: {self.y.shape}")
        logger.info(f"  Features: {self.X.columns.tolist()}")

        return self.X, self.y

    def standardize_features(self) -> pd.DataFrame:
        """Standarisasi features menggunakan StandardScaler"""
        logger.info("Processing: Standardize Features")

        if self.X is None:
            logger.error("Features not separated yet. Call separate_features_target() first")
            raise ValueError("Features not separated")

        X_scaled = self.scaler.fit_transform(self.X)
        X_scaled_df = pd.DataFrame(X_scaled, columns=self.X.columns)

        logger.info(f"  ✓ Features standardized")
        logger.info(f"  Mean: {X_scaled_df.mean().mean():.6f}")
        logger.info(f"  Std: {X_scaled_df.std().mean():.6f}")

        return X_scaled_df

    def save_preprocessed_data(self, X_scaled: pd.DataFrame) -> None:
        """Menyimpan data yang sudah diproses"""
        logger.info("Saving Preprocessed Data")

        # Save features
        features_path = os.path.join(self.output_dir, 'wine_quality_features.csv')
        X_scaled.to_csv(features_path, index=False)
        logger.info(f"  ✓ Features saved: {features_path}")

        # Save target
        target_path = os.path.join(self.output_dir, 'wine_quality_target.csv')
        self.y.to_csv(target_path, index=False)
        logger.info(f"  ✓ Target saved: {target_path}")

        # Save scaler
        import joblib
        scaler_path = os.path.join(self.output_dir, 'scaler.pkl')
        joblib.dump(self.scaler, scaler_path)
        logger.info(f"  ✓ Scaler saved: {scaler_path}")

    def run_pipeline(self, target_col: str = 'quality') -> tuple:
        """
        Menjalankan seluruh preprocessing pipeline

        Args:
            target_col (str): Nama kolom target

        Returns:
            tuple: (X_scaled, y)
        """
        logger.info("\n" + "="*60)
        logger.info("STARTING AUTOMATED PREPROCESSING PIPELINE")
        logger.info("="*60 + "\n")

        # Step 1: Load Data
        self.load_data()

        # Step 2: Handle Missing Values
        self.handle_missing_values()

        # Step 3: Remove Duplicates
        self.remove_duplicates()

        # Step 4: Detect Outliers
        self.detect_outliers()

        # Step 5: Separate Features and Target
        self.separate_features_target(target_col)

        # Step 6: Standardize Features
        X_scaled = self.standardize_features()

        # Step 7: Save Preprocessed Data
        self.save_preprocessed_data(X_scaled)

        logger.info("\n" + "="*60)
        logger.info("PREPROCESSING PIPELINE COMPLETED SUCCESSFULLY")
        logger.info("="*60 + "\n")

        return X_scaled, self.y


# ===========================
# MAIN EXECUTION
# ===========================

if __name__ == "__main__":

    # Inisialisasi preprocessor
    preprocessor = WineQualityPreprocessor(
        raw_data_path='wine_quality.csv',
        output_dir='wine_quality_preprocessing'
    )

    # Jalankan pipeline
    X_scaled, y = preprocessor.run_pipeline()

    print("\n✓ Preprocessing selesai!")
    print(f"Features shape: {X_scaled.shape}")
    print(f"Target shape: {y.shape}")